  export const stores = [
    {
      name: "Thangam Pooja Stores",
      address: "CVS Building, Metupalayam Road,\nK. Vadavumurai, Kovai - 17.",
      phone: "7373740501",
      map: "https://maps.app.goo.gl/JiQ3kUS2eTpcRcnn8",
      badge: "",
    },

    {
      name: "Manikandan Pooja Stores",
      address: "Near Ayyappan Kovil, New Siddhapudur,\nKovai - 44",
      phone: "9443776638",
      map: "https://maps.app.goo.gl/7macG6aM9TjMquq28",
      badge: "Veshti Available",
    },

    {
      name: "Shree Panjamugi Pooja Stores",
      address: "Mahalakshmi Amman Temple Street, Poomarket,\nKovai - 641001",
      phone: "9626335644",
      map: "https://maps.app.goo.gl/Ed5n4CyTWVMyJkZV9",
      badge: "Veshti Available",
    },

    {
      name: "Guru Pooja Stores",
      address: "Sundaram Street, RS Puram,\nKovai - 641001",
      phone: "9940803740",
      map: "https://maps.app.goo.gl/m45w3JyVpmJG4NyW8",
      badge: "",
    },

    {
      name: "Ravi Stores",
      address: "Chinmayanagar Main Street, Vadavalli, Coimbatore 641041",
      phone: "7339260101",
      map: "https://maps.app.goo.gl/Pfoctsy3u5nZ3FJd8",
      badge: "",
    },
    {
      name: "Real Departmental Stores",
      address: "Opp. Sree Dakshas Utkarsh Apartment, Thondamuthur Road, Vadavalli, Coimbatore - 641046",
      phone: "9894331256",
      map: "https://maps.app.goo.gl/2gr2uNS7gYWEoCVZ8",
      badge: "",
    },
    {
      name: "Saravana Stores ",
      address: "Lakshmi nagar, Vadavalli, Coimbatore",
      phone: "9842243774",
      map: "https://maps.app.goo.gl/gudkFv7CBECRhwYH6",
      badge: "",
    },
    {
      name: "Rathi's Beauty Parlour ",
      address: "No.16, Veerakeralam road, Opp. Vadavalli High School, Near Vengadeshwara Hotel, Linganoor, Vadavalli, Coimbatore - 41",
      phone: "9965782124",
      map: "https://maps.app.goo.gl/r7TcGhKkxzjShUCw9",
      badge: "",
    },
    {
      name: "Nathan Pharmacy",
      address: "Door No; 5-D, Tharun Complex, Thondamuthur Road, Coimbatore",
      phone: "9787629693",
      map: "https://maps.app.goo.gl/twQ3Rmw79DQgYsK88",
      badge: "",
    },
    {
      name: "Shape Up Ladies Gym",
      address: "No: 41/1, First floor, Jayam Complex, LGB Nagar Bus stop, Near Prozone Mall, Coimbatore - 641035",
      phone: "9790266930",
      map: "https://maps.app.goo.gl/j5f1gfHFBoH8w38A6",
      badge: "",
    },
    {
      name: "Janaki Pharma",
      address: "Ganapathy NSS Mandiram, 20 Umayalpuram, Vilankurichi Road, Opp. MGR Play Ground, Coimbatore - 641035",
      phone: "9843219878",
      map: "https://maps.app.goo.gl/j5f1gfHFBoH8w38A6",
      badge: "",
    },
    {
      name: "Rishi's Beauty Care",
      address: "No. 10/33 Amman Complex Near Dhamu Garden, S.M Palayam Road G.N Mills Coimbatore - 641029",
      phone: "8015123048",
      map: "https://maps.app.goo.gl/SYXTFhwW187Kb6Cb6",
      badge: "",
    },
    {
      name: "Rishi's Beauty Care",
      address: "No. 398, GKB Complex, Marudhamalai Main Road, Perumal Kovil Bus Stop, PN.Pudhur, Coimbatore - 641041",
      phone: "8248769344",
      map: "https://maps.app.goo.gl/aaxgQBM6yAeKpy6k8",
      badge: "",
    },
    {
      name: "Sri Mahalakshmi Stores",
      address: "Onappalayam",
      phone: "7402172544",
      map: "https://maps.app.goo.gl/rX6Pu2mCYQdtM2Fj6",
      badge: "",
    },
    {
      name: "Sri Valli Pharmacy",
      address: "Ganapathy Maanagar",
      phone: "8270346001",
      map: "https://maps.app.goo.gl/Yxx6xX1yEew4jvXR6",
      badge: "",
    },
    {
      name: "P A Store",
      address: "Ganapathy Maanagar",
      phone: "9789218785",
      map: "https://maps.app.goo.gl/nfig5Bgm1FhpMLHv8",
      badge: "",
    },
    {
      name: "Sri Aanjaneya Medicals",
      address: "Ganapathy Housing Unit, VOC Nagar, Coimbatore, Tamil Nadu 641006",
      phone: "9940889010",
      map: "https://maps.app.goo.gl/zBMPuV6432epYTPo7",
      badge: "",
    },
    {
      name: "AVM Organic Shop",
      address: "Sneha Illam, 22A, Police Quarters Rd, Bharathynagar nagar, VOC Nagar, Ganapathy, Coimbatore, Tamil Nadu 641006",
      phone: "9788174778",
      map: "https://maps.app.goo.gl/PAgt2RjTUvxtXJLX6",
      badge: "",
    },
    {
      name: "Sri Vairam Pharmacy",
      address: "42nd Ward, Velandipalayam Mandal, Kovilmedu",
      phone: "9578181100",
      map: "https://maps.app.goo.gl/5HwVyDGeFSVevRko9",
      badge: "",
    },
    {
      name: "Fresh Look Beauty Parlour",
      address: "178/82C, Vadavalli, Sri Ram Avenue, Coimbatore, Tamil Nadu 641041",
      phone: "8668072687",
      map: "https://maps.app.goo.gl/675XLyj9P6SrV2f76",
      badge: "",
    },
    {
      name: "R.R.VEGETABLES & FRUITS",
      address: "dev towers, Manikarampalayam, Ganapathy, Coimbatore, TamilNadu 641006",
      phone: "9843376963",
      map: "https://maps.app.goo.gl/zJ2ebeJFPmJT7rtA9",
      badge: "",
    },
    {
      name: "Star Pharmacy",
      address: "Ashok Nagar, Manikarampalayam, Ganapathy, Coimbatore, Tamil Nadu 641006",
      phone: "9551042563",
      map: "https://maps.app.goo.gl/PFF2e56rgsjqaqxu9",
      badge: "",
    },
    {
      name: "Sri sairam Medicals",
      address: "Sridevi Nagar, Ganapathy, Coimbatore, Tamil Nadu 641006",
      phone: "9360628275",
      map: "https://maps.app.goo.gl/MLnNfyeY5vzDbFbV9",
      badge: "",
    },
    {
      name: "Marimuthu Maligai Store",
      address: "Sridevi Nagar, Ganapathy, Coimbatore, Tamil Nadu 641006",
      phone: "9629057718",
      map: "https://maps.app.goo.gl/3sNawMCuhnWLg6uXA",
      badge: "",
    },
    {
      name: "ALLL CARE Pharmacy",
      address: "Sridevi Nagar, Ganapathy, Coimbatore, Tamil Nadu 641006",
      phone: "7418933227",
      map: "https://maps.app.goo.gl/QgsFvj8ozFxguuQ1A",
      badge: "",
    },
    {
      name: "STS Medicals",
      address: "Near S.E.S School, Mamarathottam, Ganesh Layout, Ganapathy, Coimbatore, Tamil Nadu 641006",
      phone: "9994399016",
      map: "https://maps.app.goo.gl/hZqRERdoDQB4Ahj58",
      badge: "",
    },
    {
      name: "Eswar Medicals",
      address: "PSR Building, Ganapathy, Coimbatore, Tamil Nadu 641006",
      phone: "9894364689",
      map: "https://maps.app.goo.gl/qUTdhtr73p8ByQaF6",
      badge: "",
    },
    {
      name: "MBS Store ",
      address: "Ganapathy, Coimbatore, Tamil Nadu 641006",
      phone: "9715063938",
      map: "https://maps.app.goo.gl/QEx6r4np2eL1Xkrs6",
      badge: "",
    },
    {
      name: "NEW SREE DHANALA KSHMI MEDICALS",
      address: "41/A, 41/47, Mamara Thottam, Sridevi Nagar, Ganapathy, Coimbatore, Tamil Nadu 641006",
      phone: "9894172348",
      map: "https://maps.app.goo.gl/DT13CvyWNFnFwRTY9",
      badge: "",
    },
  ];